# Enable C++ support
language: cpp

stages:
  - build

jobs:
  include:
    - stage: build
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - pip install conan
        - export PATH=$MSBUILD_PATH:$PATH
        - ./build.bat
